apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-config
    app.kubernetes.io/part-of: argo-rollouts
data:
  # Traffic router plugins for progressive delivery
  trafficRouterPlugins: |
    - name: "argoproj-labs/gatewayapi"
      location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.2.0/gateway-api-plugin-linux-amd64"
    - name: "argoproj-labs/nginx"
      location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-nginx/releases/download/v0.1.0/nginx-plugin-linux-amd64"
  
  # Metric providers for analysis
  metricProviderPlugins: |
    - name: "argoproj-labs/prometheus"
      location: "https://github.com/argoproj-labs/rollouts-plugin-metric-prometheus/releases/download/v0.1.0/prometheus-plugin-linux-amd64"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-config
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/name: argo-rollouts-notification-config
    app.kubernetes.io/part-of: argo-rollouts
data:
  # Notification configuration for rollouts
  config.yaml: |
    triggers:
      rollout-updated:
        - when: rollout.spec.template.spec.containers[0].image != rollout.status.currentPodHash
          send: [rollout-updated]
      rollout-step-completed:
        - when: rollout.status.currentStepIndex > rollout.status.currentStepIndex
          send: [rollout-step-completed]
      rollout-completed:
        - when: rollout.status.phase == "Healthy"
          send: [rollout-completed]
      rollout-aborted:
        - when: rollout.status.phase == "Degraded"
          send: [rollout-aborted]
    
    templates:
      rollout-updated: |
        message: Rollout {{.rollout.metadata.name}} has been updated
      rollout-step-completed: |
        message: Rollout {{.rollout.metadata.name}} completed step {{.rollout.status.currentStepIndex}}
      rollout-completed: |
        message: Rollout {{.rollout.metadata.name}} has completed successfully
      rollout-aborted: |
        message: Rollout {{.rollout.metadata.name}} has been aborted
    
    services:
      slack:
        token: $slack-token
      webhook:
        url: $webhook-url
        headers:
          - name: Content-Type
            value: application/json