apiVersion: v1
kind: Secret
metadata:
  name: mattailor-ai-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  # Repository URL - update with your actual repository
  url: https://github.com/your-org/mattailor-ai
  
  # For HTTPS with token authentication (GitHub, GitLab)
  username: git
  password: YOUR_PERSONAL_ACCESS_TOKEN
  
  # Alternative: SSH key authentication (uncomment and remove HTTPS config above)
  # type: git
  # sshPrivateKey: |
  #   -----BEGIN OPENSSH PRIVATE KEY-----
  #   YOUR_SSH_PRIVATE_KEY_HERE
  #   -----END OPENSSH PRIVATE KEY-----
  
  # Repository type
  type: git
  
  # Additional repository settings
  project: default
  
---
# GitHub App authentication (preferred for organizations)
apiVersion: v1
kind: Secret
metadata:
  name: mattailor-ai-github-app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  # GitHub App credentials (create a GitHub App for better access control)
  url: https://github.com/your-org
  githubAppID: "YOUR_GITHUB_APP_ID"
  githubAppInstallationID: "YOUR_GITHUB_APP_INSTALLATION_ID"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_GITHUB_APP_PRIVATE_KEY_HERE
    -----END RSA PRIVATE KEY-----