apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  # Slack integration
  slack-token: "xoxb-YOUR-SLACK-BOT-TOKEN"
  
  # Microsoft Teams webhook
  teams-webhook-url: "https://your-org.webhook.office.com/webhookb2/YOUR-TEAMS-WEBHOOK-URL"
  
  # Email configuration
  email-username: "notifications@mattailor.ai"
  email-password: "YOUR-EMAIL-APP-PASSWORD"
  
  # OIDC client secret (if using OIDC authentication)
  oidc.clientSecret: "YOUR-OIDC-CLIENT-SECRET"
  
---
# Sealed secret template (use if you have sealed-secrets controller)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    # Generate sealed secrets with:
    # echo -n "your-secret-value" | kubeseal --format yaml --name argocd-notifications-secret --namespace argocd
    slack-token: "SEALED_SECRET_DATA_HERE"
    teams-webhook-url: "SEALED_SECRET_DATA_HERE"
    email-username: "SEALED_SECRET_DATA_HERE"
    email-password: "SEALED_SECRET_DATA_HERE"
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque