apiVersion: v1
kind: ResourceQuota
metadata:
  name: argocd-quota
  namespace: argocd
spec:
  hard:
    # Compute resources
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    
    # Storage
    requests.storage: 20Gi
    persistentvolumeclaims: "5"
    
    # Object counts
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    
    # Networking
    services.loadbalancers: "2"
    services.nodeports: "0"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: argocd-limits
  namespace: argocd
spec:
  limits:
  # Pod limits
  - type: Pod
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  
  # Container limits
  - type: Container
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  
  # PVC limits
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi

---
# Production environment resource quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mattailor-prod-quota
  namespace: mattailor-ai-prod
spec:
  hard:
    # Compute resources
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    
    # Storage
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # Object counts
    pods: "50"
    services: "20"
    secrets: "30"
    configmaps: "30"
    
    # Networking
    services.loadbalancers: "3"
    services.nodeports: "0"

---
# Staging environment resource quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mattailor-staging-quota
  namespace: mattailor-ai-staging
spec:
  hard:
    # Compute resources
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    
    # Storage
    requests.storage: 50Gi
    persistentvolumeclaims: "5"
    
    # Object counts
    pods: "30"
    services: "15"
    secrets: "20"
    configmaps: "20"
    
    # Networking
    services.loadbalancers: "2"
    services.nodeports: "0"

---
# Development environment resource quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mattailor-dev-quota
  namespace: mattailor-ai-dev
spec:
  hard:
    # Compute resources
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    
    # Storage
    requests.storage: 20Gi
    persistentvolumeclaims: "3"
    
    # Object counts
    pods: "20"
    services: "10"
    secrets: "15"
    configmaps: "15"
    
    # Networking
    services.loadbalancers: "1"
    services.nodeports: "0"