apiVersion: v1
kind: ConfigMap
metadata:
  name: mattailor-config
  namespace: mattailor-ai
data:
  # Frontend configuration
  REACT_APP_API_URL: "http://mattailor-backend-service:8000"
  REACT_APP_VERSION: "1.0.0"
  
  # Backend configuration
  CORS_ORIGINS: "http://localhost:3000,https://mattailor-ai.com"
  LOG_LEVEL: "info"
  MAX_REQUEST_SIZE: "10MB"
  
  # AI/ML configuration
  MODEL_CACHE_SIZE: "1000"
  PREDICTION_TIMEOUT: "30"
  
  # Material database configuration
  MATERIAL_CACHE_TTL: "3600"
  MAX_MATERIALS_PER_QUERY: "100"