apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mattailor-ai-ingress
  namespace: mattailor-ai
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - mattailor-ai.yourdomain.com
    secretName: mattailor-ai-tls
  rules:
  - host: mattailor-ai.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mattailor-ai-service
            port:
              number: 80