apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - persistent-volume.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - service-monitor.yaml

namespace: mattailor-ai

commonLabels:
  app.kubernetes.io/name: mattailor-ai
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: web-application

images:
  - name: mattailor-ai/frontend
    newTag: latest
  - name: mattailor-ai/backend
    newTag: latest