apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattailor-pv
  namespace: mattailor-ai
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/mattailor
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattailor-pvc
  namespace: mattailor-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd