apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: mattailor-ai
type: Opaque
data:
  # Base64 encoded API keys - replace with your actual encoded keys
  matweb-api-key: <BASE64_ENCODED_MATWEB_API_KEY>
  materials-project-api-key: <BASE64_ENCODED_MATERIALS_PROJECT_API_KEY>
  
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: mattailor-ai
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>