apiVersion: v1
kind: Service
metadata:
  name: mattailor-frontend-service
  namespace: ${NAMESPACE:-mattailor}
  labels:
    app: mattailor-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: mattailor-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: mattailor-frontend-headless
  namespace: ${NAMESPACE:-mattailor}
  labels:
    app: mattailor-frontend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: mattailor-frontend