apiVersion: v1
kind: Service
metadata:
  name: mattailor-frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: mattailor-backend-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800