apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - persistent-volume.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - service.yaml

namespace: mattailor-ai

commonLabels:
  app.kubernetes.io/name: mattailor-ai
  app.kubernetes.io/component: web-application

# Base configuration - environment-specific values will be overridden in overlays