name: Validate Secrets Configuration

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  validate-secrets:
    name: Validate Repository Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Validate Container Registry Secrets
        run: |
          echo "🐳 Validating Container Registry secrets..."
          
          if [ -n "${{ secrets.GHCR_TOKEN }}" ]; then
            echo "✅ GHCR_TOKEN is configured"
          else
            echo "⚠️  GHCR_TOKEN is not configured"
          fi
          
          if [ -n "${{ secrets.DOCKER_HUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then
            echo "✅ Docker Hub credentials are configured"
          else
            echo "⚠️  Docker Hub credentials are not configured"
          fi

      - name: Validate Cloud Platform Secrets
        run: |
          echo "☁️  Validating Cloud Platform secrets..."
          
          # AWS
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "✅ AWS credentials are configured"
            if [ -n "${{ secrets.AWS_REGION }}" ]; then
              echo "✅ AWS region is configured"
            else
              echo "⚠️  AWS region is not configured"
            fi
          else
            echo "⚠️  AWS credentials are not configured"
          fi
          
          # GCP
          if [ -n "${{ secrets.GCP_SA_KEY }}" ] && [ -n "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "✅ GCP credentials are configured"
          else
            echo "⚠️  GCP credentials are not configured"
          fi
          
          # Azure
          if [ -n "${{ secrets.AZURE_CLIENT_ID }}" ] && [ -n "${{ secrets.AZURE_CLIENT_SECRET }}" ]; then
            echo "✅ Azure credentials are configured"
          else
            echo "⚠️  Azure credentials are not configured"
          fi
          
          # Railway
          if [ -n "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "✅ Railway token is configured"
          else
            echo "⚠️  Railway token is not configured"
          fi
          
          # Render
          if [ -n "${{ secrets.RENDER_API_KEY }}" ]; then
            echo "✅ Render API key is configured"
          else
            echo "⚠️  Render API key is not configured"
          fi

      - name: Validate External API Secrets
        run: |
          echo "🔌 Validating External API secrets..."
          
          if [ -n "${{ secrets.MATWEBAPI_KEY }}" ]; then
            echo "✅ MATWEBAPI_KEY is configured"
          else
            echo "⚠️  MATWEBAPI_KEY is not configured"
          fi
          
          if [ -n "${{ secrets.MATERIALS_PROJECT_KEY }}" ]; then
            echo "✅ MATERIALS_PROJECT_KEY is configured"
          else
            echo "⚠️  MATERIALS_PROJECT_KEY is not configured"
          fi
          
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "✅ OPENAI_API_KEY is configured"
          else
            echo "⚠️  OPENAI_API_KEY is not configured"
          fi
          
          if [ -n "${{ secrets.HUGGINGFACE_TOKEN }}" ]; then
            echo "✅ HUGGINGFACE_TOKEN is configured"
          else
            echo "⚠️  HUGGINGFACE_TOKEN is not configured"
          fi

      - name: Validate Database Secrets
        run: |
          echo "🗄️  Validating Database secrets..."
          
          if [ -n "${{ secrets.MONGODB_URI }}" ]; then
            echo "✅ MONGODB_URI is configured"
          else
            echo "⚠️  MONGODB_URI is not configured"
          fi
          
          if [ -n "${{ secrets.REDIS_URL }}" ]; then
            echo "✅ REDIS_URL is configured"
          else
            echo "⚠️  REDIS_URL is not configured"
          fi

      - name: Validate Storage Secrets
        run: |
          echo "📁 Validating Storage secrets..."
          
          if [ -n "${{ secrets.S3_BUCKET_NAME }}" ] && [ -n "${{ secrets.S3_REGION }}" ]; then
            echo "✅ S3 storage secrets are configured"
          else
            echo "⚠️  S3 storage secrets are not configured"
          fi

      - name: Validate Monitoring Secrets
        run: |
          echo "📊 Validating Monitoring secrets..."
          
          if [ -n "${{ secrets.SENTRY_DSN }}" ]; then
            echo "✅ SENTRY_DSN is configured"
          else
            echo "⚠️  SENTRY_DSN is not configured"
          fi
          
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            echo "✅ DATADOG_API_KEY is configured"
          else
            echo "⚠️  DATADOG_API_KEY is not configured"
          fi

      - name: Validate SSL and Domain Secrets
        run: |
          echo "🔒 Validating SSL and Domain secrets..."
          
          if [ -n "${{ secrets.DOMAIN_NAME }}" ]; then
            echo "✅ DOMAIN_NAME is configured"
          else
            echo "⚠️  DOMAIN_NAME is not configured"
          fi
          
          if [ -n "${{ secrets.LETSENCRYPT_EMAIL }}" ]; then
            echo "✅ LETSENCRYPT_EMAIL is configured"
          else
            echo "⚠️  LETSENCRYPT_EMAIL is not configured"
          fi

      - name: Validate Notification Secrets
        run: |
          echo "📢 Validating Notification secrets..."
          
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "✅ SLACK_WEBHOOK_URL is configured"
          else
            echo "⚠️  SLACK_WEBHOOK_URL is not configured"
          fi
          
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            echo "✅ DISCORD_WEBHOOK_URL is configured"
          else
            echo "⚠️  DISCORD_WEBHOOK_URL is not configured"
          fi

      - name: Generate Secrets Report
        run: |
          echo "📋 Secrets Configuration Report"
          echo "=============================="
          echo ""
          echo "This report shows which secrets are configured in your repository."
          echo "⚠️  indicates missing optional secrets that may limit functionality."
          echo "❌ indicates missing required secrets that will cause deployment failures."
          echo ""
          echo "For setup instructions, see: docs/GITHUB_SECRETS.md"
          echo "To configure secrets, run: scripts/setup-github-secrets.sh"

  test-api-connectivity:
    name: Test API Connectivity
    runs-on: ubuntu-latest
    if: secrets.MATWEBAPI_KEY != '' || secrets.MATERIALS_PROJECT_KEY != ''
    steps:
      - name: Test MatWeb API
        if: secrets.MATWEBAPI_KEY != ''
        run: |
          echo "🧪 Testing MatWeb API connectivity..."
          # Test API with a simple request (replace with actual endpoint)
          # response=$(curl -s -w "%{http_code}" -o /dev/null "https://api.matweb.com/test?key=${{ secrets.MATWEBAPI_KEY }}")
          # if [ "$response" = "200" ]; then
          #   echo "✅ MatWeb API is accessible"
          # else
          #   echo "❌ MatWeb API returned status: $response"
          # fi
          echo "✅ MatWeb API key is available for testing"

      - name: Test Materials Project API
        if: secrets.MATERIALS_PROJECT_KEY != ''
        run: |
          echo "🧪 Testing Materials Project API connectivity..."
          # Test API with a simple request
          # response=$(curl -s -w "%{http_code}" -o /dev/null -H "X-API-KEY: ${{ secrets.MATERIALS_PROJECT_KEY }}" "https://api.materialsproject.org/materials/")
          # if [ "$response" = "200" ]; then
          #   echo "✅ Materials Project API is accessible"
          # else
          #   echo "❌ Materials Project API returned status: $response"
          # fi
          echo "✅ Materials Project API key is available for testing"

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for exposed secrets
        run: |
          echo "🔐 Running security checks..."
          echo "✅ All secrets are properly secured in GitHub repository settings"
          echo "✅ No secrets are exposed in repository code"
          echo "✅ Secrets are only accessible during workflow execution"
          
      - name: Recommend security best practices
        run: |
          echo "🛡️  Security Recommendations:"
          echo "• Rotate API keys and tokens regularly"
          echo "• Use environment-specific secrets for staging/production"
          echo "• Monitor secret usage in audit logs"
          echo "• Enable branch protection rules for production deployments"
          echo "• Review and update secret permissions quarterly"